# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a1480d0c24e5941a225d0a18d44ed538a9c90871dcba21d5b304607c007de935a70fb6e70382a2ff19d8e782d69016b1b8d5bc81ad3d8b70f06d314d5f0b3c

test:
  secret_key_base: 458ca17d1c9980ac61f383e52c5b37ac6797c7727712bc72142dd8319540709169c2716d3f95bf5b2f6b19d3a5dcf4f1020a10abc9590b3e42ea6c2cdc780c89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
